name: car_connect
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.3+8

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  flutter_svg: ^2.0.10+1
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.3
  http: ^1.1.0
  get_it: ^7.6.4
  connectivity_plus: ^6.1.3
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  shimmer: ^3.0.0
  dots_indicator: ^3.0.0
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  open_store: ^0.5.0
  flutter_exit_app: ^1.1.2
  dropdown_button2: ^2.3.9
  dynamic_height_grid_view: ^0.0.4
  dotted_button: ^0.0.2
  flash: ^3.1.1
  flutter_expanded_tile: ^0.4.0
  pinput: ^4.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  file_picker:
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  geolocator:
dev_dependencies:
  flutter_test:
    sdk: flutter
  launcher_name: ^1.0.2



  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.otf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic.ttf

